apiVersion: apps/v1
kind: Deployment
metadata:
  name: ass2load
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: swe645-2
        image: spore2/swe645a2:latest
        ports:
        - containerPort: 80
