apiVersion: v1
kind: Config
clusters:
- name: "ass2"
  cluster:
    server: "https://52.70.36.61/k8s/clusters/c-m-vwnn848h"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2RENDQ\
      VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
      GN3T1RBNApNVGs1T1RBZUZ3MHlOREF5TWpnd01EVTVOVGxhRncwek5EQXlNalV3TURVNU5UbGFNR\
      Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
      1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE56QTVNRGd4T1RrNU1Ga3dFd1lIS29aSXpqMENBU\
      VlJS29aSXpqMERBUWNEUWdBRUxpcngxY05KODhZdgpBeGdZK01YTDJwMFl4N0tHUlNRV01HTExwd\
      1pFUjdwWTJ3TklZL2VDN2p0R2NrL3JrMldPcVlZQlBBdXIyTlNoCkJMbEU4dmFMdWFOQ01FQXdEZ\
      1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGT\
      EU3dVBXVXNhN0loNEw5c3EyWnBZQ1ExMGh1TUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSURZeQpKd\
      U16bEdiTS9JMXBiM3lwbU5Ub2dEOFhuMC9WK1Z1SFhhNVZnS0lKQWlCaEhmaGRyTmRvV1Y5NHlCO\
      UVEN1BICjJsNjlTRHhuZVhaVlNHbWVCQ2l3VWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"

users:
- name: "ass2"
  user:
    token: "kubeconfig-user-w8dsnln2w4:qhkgtfvqg2q4mgqm795hlnzmk479n4qm456q9bgjgg9h75pz68mp2n"


contexts:
- name: "ass2"
  context:
    user: "ass2"
    cluster: "ass2"

current-context: "ass2"
